# Database
db.url=jdbc:h2:~/lucky-pos/db;AUTO_SERVER=TRUE
db.driver=org.h2.Driver
db.username=sa
db.password=

# HikariCP
hikari.pool.size=10
hikari.timeout=30000

# App
app.name=Lucky POS
app.version=1.0