/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables.records;


import com.turboboostteam.pos.jooq.tables.Customers;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.PHONE</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.PHONE</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.LOYALTY_POINTS</code>.
     */
    public void setLoyaltyPoints(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.LOYALTY_POINTS</code>.
     */
    public Integer getLoyaltyPoints() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.LOYALTY_TIER</code>.
     */
    public void setLoyaltyTier(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.LOYALTY_TIER</code>.
     */
    public String getLoyaltyTier() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.TOTAL_SPENT</code>.
     */
    public void setTotalSpent(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.TOTAL_SPENT</code>.
     */
    public BigDecimal getTotalSpent() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.ACTIVE</code>.
     */
    public void setActive(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.ACTIVE</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMERS.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMERS.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Long id, String firstName, String lastName, String email, String phone, Integer loyaltyPoints, String loyaltyTier, BigDecimal totalSpent, Boolean active, LocalDateTime createdAt) {
        super(Customers.CUSTOMERS);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setPhone(phone);
        setLoyaltyPoints(loyaltyPoints);
        setLoyaltyTier(loyaltyTier);
        setTotalSpent(totalSpent);
        setActive(active);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
