/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables.records;


import com.turboboostteam.pos.jooq.tables.Discounts;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DiscountsRecord extends UpdatableRecordImpl<DiscountsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.CODE</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.CODE</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.DISCOUNT_TYPE</code>.
     */
    public void setDiscountType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.DISCOUNT_TYPE</code>.
     */
    public String getDiscountType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.DISCOUNT_VALUE</code>.
     */
    public void setDiscountValue(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.DISCOUNT_VALUE</code>.
     */
    public BigDecimal getDiscountValue() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.MIN_PURCHASE</code>.
     */
    public void setMinPurchase(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.MIN_PURCHASE</code>.
     */
    public BigDecimal getMinPurchase() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.ACTIVE</code>.
     */
    public void setActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.ACTIVE</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.VALID_FROM</code>.
     */
    public void setValidFrom(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.VALID_FROM</code>.
     */
    public LocalDateTime getValidFrom() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.VALID_UNTIL</code>.
     */
    public void setValidUntil(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.VALID_UNTIL</code>.
     */
    public LocalDateTime getValidUntil() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiscountsRecord
     */
    public DiscountsRecord() {
        super(Discounts.DISCOUNTS);
    }

    /**
     * Create a detached, initialised DiscountsRecord
     */
    public DiscountsRecord(Long id, String code, String name, String discountType, BigDecimal discountValue, BigDecimal minPurchase, Boolean active, LocalDateTime validFrom, LocalDateTime validUntil, LocalDateTime createdAt) {
        super(Discounts.DISCOUNTS);

        setId(id);
        setCode(code);
        setName(name);
        setDiscountType(discountType);
        setDiscountValue(discountValue);
        setMinPurchase(minPurchase);
        setActive(active);
        setValidFrom(validFrom);
        setValidUntil(validUntil);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
