/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables.records;


import com.turboboostteam.pos.jooq.tables.InventoryStock;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryStockRecord extends UpdatableRecordImpl<InventoryStockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.INVENTORY_STOCK.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.INVENTORY_STOCK.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.INVENTORY_STOCK.PRODUCT_ID</code>.
     */
    public void setProductId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.INVENTORY_STOCK.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.INVENTORY_STOCK.QUANTITY</code>.
     */
    public void setQuantity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.INVENTORY_STOCK.QUANTITY</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.INVENTORY_STOCK.LOW_STOCK_THRESHOLD</code>.
     */
    public void setLowStockThreshold(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.INVENTORY_STOCK.LOW_STOCK_THRESHOLD</code>.
     */
    public Integer getLowStockThreshold() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.INVENTORY_STOCK.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.INVENTORY_STOCK.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryStockRecord
     */
    public InventoryStockRecord() {
        super(InventoryStock.INVENTORY_STOCK);
    }

    /**
     * Create a detached, initialised InventoryStockRecord
     */
    public InventoryStockRecord(Long id, Long productId, Integer quantity, Integer lowStockThreshold, LocalDateTime updatedAt) {
        super(InventoryStock.INVENTORY_STOCK);

        setId(id);
        setProductId(productId);
        setQuantity(quantity);
        setLowStockThreshold(lowStockThreshold);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
