/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables.records;


import com.turboboostteam.pos.jooq.tables.Payments;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PaymentsRecord extends UpdatableRecordImpl<PaymentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.PAYMENTS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENTS.SALE_ID</code>.
     */
    public void setSaleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTS.SALE_ID</code>.
     */
    public Long getSaleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENTS.PAYMENT_TYPE</code>.
     */
    public void setPaymentType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTS.PAYMENT_TYPE</code>.
     */
    public String getPaymentType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENTS.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTS.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENTS.CURRENCY</code>.
     */
    public void setCurrency(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTS.CURRENCY</code>.
     */
    public String getCurrency() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENTS.REFERENCE</code>.
     */
    public void setReference(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTS.REFERENCE</code>.
     */
    public String getReference() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENTS.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTS.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentsRecord
     */
    public PaymentsRecord() {
        super(Payments.PAYMENTS);
    }

    /**
     * Create a detached, initialised PaymentsRecord
     */
    public PaymentsRecord(Long id, Long saleId, String paymentType, BigDecimal amount, String currency, String reference, LocalDateTime createdAt) {
        super(Payments.PAYMENTS);

        setId(id);
        setSaleId(saleId);
        setPaymentType(paymentType);
        setAmount(amount);
        setCurrency(currency);
        setReference(reference);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
