/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables.records;


import com.turboboostteam.pos.jooq.tables.Products;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.PRODUCTS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.PRODUCTS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.PRODUCTS.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.PRODUCTS.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.PRODUCTS.BARCODE</code>.
     */
    public void setBarcode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.PRODUCTS.BARCODE</code>.
     */
    public String getBarcode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.PRODUCTS.PRICE</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.PRODUCTS.PRICE</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>PUBLIC.PRODUCTS.CURRENCY</code>.
     */
    public void setCurrency(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.PRODUCTS.CURRENCY</code>.
     */
    public String getCurrency() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.PRODUCTS.PRODUCT_TYPE</code>.
     */
    public void setProductType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.PRODUCTS.PRODUCT_TYPE</code>.
     */
    public String getProductType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.PRODUCTS.CATEGORY_ID</code>.
     */
    public void setCategoryId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.PRODUCTS.CATEGORY_ID</code>.
     */
    public Long getCategoryId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>PUBLIC.PRODUCTS.ACTIVE</code>.
     */
    public void setActive(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.PRODUCTS.ACTIVE</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>PUBLIC.PRODUCTS.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.PRODUCTS.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(Long id, String name, String barcode, BigDecimal price, String currency, String productType, Long categoryId, Boolean active, LocalDateTime createdAt) {
        super(Products.PRODUCTS);

        setId(id);
        setName(name);
        setBarcode(barcode);
        setPrice(price);
        setCurrency(currency);
        setProductType(productType);
        setCategoryId(categoryId);
        setActive(active);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
