/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables.records;


import com.turboboostteam.pos.jooq.tables.SaleItems;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SaleItemsRecord extends UpdatableRecordImpl<SaleItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.SALE_ID</code>.
     */
    public void setSaleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.SALE_ID</code>.
     */
    public Long getSaleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.PRODUCT_ID</code>.
     */
    public void setProductId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.PRODUCT_NAME</code>.
     */
    public void setProductName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.PRODUCT_NAME</code>.
     */
    public String getProductName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.QUANTITY</code>.
     */
    public void setQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.QUANTITY</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.UNIT_PRICE</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.UNIT_PRICE</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.TAX_AMOUNT</code>.
     */
    public void setTaxAmount(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.TAX_AMOUNT</code>.
     */
    public BigDecimal getTaxAmount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.DISCOUNT_AMOUNT</code>.
     */
    public void setDiscountAmount(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.DISCOUNT_AMOUNT</code>.
     */
    public BigDecimal getDiscountAmount() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.LINE_TOTAL</code>.
     */
    public void setLineTotal(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.LINE_TOTAL</code>.
     */
    public BigDecimal getLineTotal() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>PUBLIC.SALE_ITEMS.CURRENCY</code>.
     */
    public void setCurrency(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.SALE_ITEMS.CURRENCY</code>.
     */
    public String getCurrency() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SaleItemsRecord
     */
    public SaleItemsRecord() {
        super(SaleItems.SALE_ITEMS);
    }

    /**
     * Create a detached, initialised SaleItemsRecord
     */
    public SaleItemsRecord(Long id, Long saleId, Long productId, String productName, Integer quantity, BigDecimal unitPrice, BigDecimal taxAmount, BigDecimal discountAmount, BigDecimal lineTotal, String currency) {
        super(SaleItems.SALE_ITEMS);

        setId(id);
        setSaleId(saleId);
        setProductId(productId);
        setProductName(productName);
        setQuantity(quantity);
        setUnitPrice(unitPrice);
        setTaxAmount(taxAmount);
        setDiscountAmount(discountAmount);
        setLineTotal(lineTotal);
        setCurrency(currency);
        resetChangedOnNotNull();
    }
}
