/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables.records;


import com.turboboostteam.pos.jooq.tables.Sales;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SalesRecord extends UpdatableRecordImpl<SalesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.SALES.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.SALES.SALE_NUMBER</code>.
     */
    public void setSaleNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.SALE_NUMBER</code>.
     */
    public String getSaleNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.SALES.CASHIER_ID</code>.
     */
    public void setCashierId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.CASHIER_ID</code>.
     */
    public Long getCashierId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.SALES.STATUS</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.SALES.SUBTOTAL</code>.
     */
    public void setSubtotal(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.SUBTOTAL</code>.
     */
    public BigDecimal getSubtotal() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>PUBLIC.SALES.TAX_AMOUNT</code>.
     */
    public void setTaxAmount(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.TAX_AMOUNT</code>.
     */
    public BigDecimal getTaxAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>PUBLIC.SALES.DISCOUNT_AMOUNT</code>.
     */
    public void setDiscountAmount(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.DISCOUNT_AMOUNT</code>.
     */
    public BigDecimal getDiscountAmount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>PUBLIC.SALES.TOTAL_AMOUNT</code>.
     */
    public void setTotalAmount(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.TOTAL_AMOUNT</code>.
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>PUBLIC.SALES.CURRENCY</code>.
     */
    public void setCurrency(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.CURRENCY</code>.
     */
    public String getCurrency() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.SALES.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>PUBLIC.SALES.COMPLETED_AT</code>.
     */
    public void setCompletedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.SALES.COMPLETED_AT</code>.
     */
    public LocalDateTime getCompletedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalesRecord
     */
    public SalesRecord() {
        super(Sales.SALES);
    }

    /**
     * Create a detached, initialised SalesRecord
     */
    public SalesRecord(Long id, String saleNumber, Long cashierId, String status, BigDecimal subtotal, BigDecimal taxAmount, BigDecimal discountAmount, BigDecimal totalAmount, String currency, LocalDateTime createdAt, LocalDateTime completedAt) {
        super(Sales.SALES);

        setId(id);
        setSaleNumber(saleNumber);
        setCashierId(cashierId);
        setStatus(status);
        setSubtotal(subtotal);
        setTaxAmount(taxAmount);
        setDiscountAmount(discountAmount);
        setTotalAmount(totalAmount);
        setCurrency(currency);
        setCreatedAt(createdAt);
        setCompletedAt(completedAt);
        resetChangedOnNotNull();
    }
}
