/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables.records;


import com.turboboostteam.pos.jooq.tables.StockMovements;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StockMovementsRecord extends UpdatableRecordImpl<StockMovementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.STOCK_MOVEMENTS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.STOCK_MOVEMENTS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.STOCK_MOVEMENTS.PRODUCT_ID</code>.
     */
    public void setProductId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.STOCK_MOVEMENTS.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.STOCK_MOVEMENTS.MOVEMENT_TYPE</code>.
     */
    public void setMovementType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.STOCK_MOVEMENTS.MOVEMENT_TYPE</code>.
     */
    public String getMovementType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.STOCK_MOVEMENTS.QUANTITY_CHANGE</code>.
     */
    public void setQuantityChange(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.STOCK_MOVEMENTS.QUANTITY_CHANGE</code>.
     */
    public Integer getQuantityChange() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.STOCK_MOVEMENTS.NOTES</code>.
     */
    public void setNotes(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.STOCK_MOVEMENTS.NOTES</code>.
     */
    public String getNotes() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.STOCK_MOVEMENTS.CREATED_BY</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.STOCK_MOVEMENTS.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.STOCK_MOVEMENTS.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.STOCK_MOVEMENTS.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StockMovementsRecord
     */
    public StockMovementsRecord() {
        super(StockMovements.STOCK_MOVEMENTS);
    }

    /**
     * Create a detached, initialised StockMovementsRecord
     */
    public StockMovementsRecord(Long id, Long productId, String movementType, Integer quantityChange, String notes, String createdBy, LocalDateTime createdAt) {
        super(StockMovements.STOCK_MOVEMENTS);

        setId(id);
        setProductId(productId);
        setMovementType(movementType);
        setQuantityChange(quantityChange);
        setNotes(notes);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
