package com.turboboostteam.pos.ui.util;

import com.turboboostteam.pos.model.report.*;
import org.apache.pdfbox.pdmodel.*;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;

public class ReportGenerator {

    private static final float PAGE_WIDTH  =
            PDRectangle.A4.getWidth();
    private static final float PAGE_HEIGHT =
            PDRectangle.A4.getHeight();
    private static final float MARGIN = 40f;
    private static final float LINE_H = 16f;

    public static File generateDailyReport(
            DailySalesReport report) throws IOException {

        PDDocument doc = new PDDocument();
        PDPage page = new PDPage(PDRectangle.A4);
        doc.addPage(page);

        PDPageContentStream cs =
                new PDPageContentStream(doc, page);

        PDType1Font bold = new PDType1Font(
                Standard14Fonts.FontName.HELVETICA_BOLD);
        PDType1Font normal = new PDType1Font(
                Standard14Fonts.FontName.HELVETICA);
        PDType1Font mono = new PDType1Font(
                Standard14Fonts.FontName.COURIER);

        float y = PAGE_HEIGHT - MARGIN;

        // ── Header ──
        y = drawText(cs, bold, 18,
                "LUCKY POS — Daily Sales Report", y);
        y = drawText(cs, normal, 11,
                "Date: " + report.getDate()
                        .format(DateTimeFormatter
                                .ofPattern("dd MMMM yyyy")),
                y - 4);
        y = drawText(cs, normal, 11,
                "Generated by: "
                        + report.getCashierName(), y);
        y = drawLine(cs, y - 8);

        // ── Summary ──
        y = drawText(cs, bold, 13,
                "Summary", y - 8);
        y = drawTwoCol(cs, normal, 11,
                "Total Transactions:",
                String.valueOf(
                        report.getTotalTransactions()),
                y - 4);
        y = drawTwoCol(cs, normal, 11,
                "Total Revenue:",
                "USD " + report.getTotalRevenue()
                        .setScale(2,
                                java.math.RoundingMode
                                        .HALF_UP),
                y);
        y = drawTwoCol(cs, normal, 11,
                "Total Tax Collected:",
                "USD " + report.getTotalTax()
                        .setScale(2,
                                java.math.RoundingMode
                                        .HALF_UP),
                y);
        y = drawTwoCol(cs, normal, 11,
                "Total Discounts Given:",
                "USD " + report.getTotalDiscount()
                        .setScale(2,
                                java.math.RoundingMode
                                        .HALF_UP),
                y);
        y = drawLine(cs, y - 4);
        y = drawTwoCol(cs, bold, 13,
                "Net Revenue:",
                "USD " + report.getNetRevenue()
                        .setScale(2,
                                java.math.RoundingMode
                                        .HALF_UP),
                y - 4);
        y = drawLine(cs, y - 8);

        // ── Top Products ──
        y = drawText(cs, bold, 13,
                "Top Products", y - 8);
        y = drawText(cs, mono, 9,
                padRight("Product", 30)
                        + padLeft("Qty", 8)
                        + padLeft("Revenue", 12),
                y - 4);
        y = drawLine(cs, y - 2);

        for (SaleReportItem item
                : report.getTopProducts()) {
            String name = item.getProductName();
            if (name.length() > 28)
                name = name.substring(0, 28);
            y = drawText(cs, mono, 9,
                    padRight(name, 30)
                            + padLeft(String.valueOf(
                            item.getQuantitySold()), 8)
                            + padLeft("USD " + item.getRevenue()
                            .setScale(2,
                                    java.math.RoundingMode
                                            .HALF_UP), 12),
                    y);
        }

        y = drawLine(cs, y - 8);

        // ── Hourly Breakdown ──
        y = drawText(cs, bold, 13,
                "Hourly Breakdown", y - 8);
        y = drawText(cs, mono, 9,
                padRight("Hour", 12)
                        + padLeft("Transactions", 15)
                        + padLeft("Revenue", 12),
                y - 4);
        y = drawLine(cs, y - 2);

        for (HourlySale hour : report.getHourlySales()) {
            y = drawText(cs, mono, 9,
                    padRight(hour.getHourLabel(), 12)
                            + padLeft(String.valueOf(
                            hour.getTransactions()), 15)
                            + padLeft("USD " + hour.getRevenue()
                            .setScale(2,
                                    java.math.RoundingMode
                                            .HALF_UP), 12),
                    y);
        }

        // ── Footer ──
        cs.beginText();
        cs.setFont(normal, 9);
        cs.newLineAtOffset(MARGIN,
                MARGIN / 2);
        cs.showText("Lucky POS — Confidential Report — "
                + java.time.LocalDateTime.now()
                .format(DateTimeFormatter
                        .ofPattern(
                                "dd/MM/yyyy HH:mm")));
        cs.endText();

        cs.close();

        File file = File.createTempFile(
                "daily_report_"
                        + report.getDate(), ".pdf");
        doc.save(file);
        doc.close();

        return file;
    }

    // ── Drawing helpers ──
    private static float drawText(
            PDPageContentStream cs,
            PDType1Font font, float size,
            String text, float y)
            throws IOException {
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset(MARGIN, y);
        cs.showText(text);
        cs.endText();
        return y - LINE_H;
    }

    private static float drawTwoCol(
            PDPageContentStream cs,
            PDType1Font font, float size,
            String left, String right, float y)
            throws IOException {
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset(MARGIN, y);
        cs.showText(left);
        cs.endText();

        float rw = font.getStringWidth(right)
                / 1000 * size;
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset(
                PAGE_WIDTH - MARGIN - rw, y);
        cs.showText(right);
        cs.endText();
        return y - LINE_H;
    }

    private static float drawLine(
            PDPageContentStream cs, float y)
            throws IOException {
        cs.moveTo(MARGIN, y);
        cs.lineTo(PAGE_WIDTH - MARGIN, y);
        cs.stroke();
        return y - 4;
    }

    private static String padRight(String s, int n) {
        return String.format("%-" + n + "s", s);
    }

    private static String padLeft(String s, int n) {
        return String.format("%" + n + "s", s);
    }
}