/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables;


import com.turboboostteam.pos.jooq.Keys;
import com.turboboostteam.pos.jooq.Public;
import com.turboboostteam.pos.jooq.tables.records.CustomersRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Customers extends TableImpl<CustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.CUSTOMERS</code>
     */
    public static final Customers CUSTOMERS = new Customers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomersRecord> getRecordType() {
        return CustomersRecord.class;
    }

    /**
     * The column <code>PUBLIC.CUSTOMERS.ID</code>.
     */
    public final TableField<CustomersRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.CUSTOMERS.FIRST_NAME</code>.
     */
    public final TableField<CustomersRecord, String> FIRST_NAME = createField(DSL.name("FIRST_NAME"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CUSTOMERS.LAST_NAME</code>.
     */
    public final TableField<CustomersRecord, String> LAST_NAME = createField(DSL.name("LAST_NAME"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CUSTOMERS.EMAIL</code>.
     */
    public final TableField<CustomersRecord, String> EMAIL = createField(DSL.name("EMAIL"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CUSTOMERS.PHONE</code>.
     */
    public final TableField<CustomersRecord, String> PHONE = createField(DSL.name("PHONE"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>PUBLIC.CUSTOMERS.LOYALTY_POINTS</code>.
     */
    public final TableField<CustomersRecord, Integer> LOYALTY_POINTS = createField(DSL.name("LOYALTY_POINTS"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.CUSTOMERS.LOYALTY_TIER</code>.
     */
    public final TableField<CustomersRecord, String> LOYALTY_TIER = createField(DSL.name("LOYALTY_TIER"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'BRONZE'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.CUSTOMERS.TOTAL_SPENT</code>.
     */
    public final TableField<CustomersRecord, BigDecimal> TOTAL_SPENT = createField(DSL.name("TOTAL_SPENT"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>PUBLIC.CUSTOMERS.ACTIVE</code>.
     */
    public final TableField<CustomersRecord, Boolean> ACTIVE = createField(DSL.name("ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>PUBLIC.CUSTOMERS.CREATED_AT</code>.
     */
    public final TableField<CustomersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Customers(Name alias, Table<CustomersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Customers(Name alias, Table<CustomersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.CUSTOMERS</code> table reference
     */
    public Customers(String alias) {
        this(DSL.name(alias), CUSTOMERS);
    }

    /**
     * Create an aliased <code>PUBLIC.CUSTOMERS</code> table reference
     */
    public Customers(Name alias) {
        this(alias, CUSTOMERS);
    }

    /**
     * Create a <code>PUBLIC.CUSTOMERS</code> table reference
     */
    public Customers() {
        this(DSL.name("CUSTOMERS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CustomersRecord, Long> getIdentity() {
        return (Identity<CustomersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CustomersRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_62;
    }

    @Override
    public List<UniqueKey<CustomersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_626, Keys.CONSTRAINT_6268);
    }

    @Override
    public Customers as(String alias) {
        return new Customers(DSL.name(alias), this);
    }

    @Override
    public Customers as(Name alias) {
        return new Customers(alias, this);
    }

    @Override
    public Customers as(Table<?> alias) {
        return new Customers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(String name) {
        return new Customers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(Name name) {
        return new Customers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(Table<?> name) {
        return new Customers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Condition condition) {
        return new Customers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
