/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables;


import com.turboboostteam.pos.jooq.Keys;
import com.turboboostteam.pos.jooq.Public;
import com.turboboostteam.pos.jooq.tables.records.DiscountsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Discounts extends TableImpl<DiscountsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.DISCOUNTS</code>
     */
    public static final Discounts DISCOUNTS = new Discounts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DiscountsRecord> getRecordType() {
        return DiscountsRecord.class;
    }

    /**
     * The column <code>PUBLIC.DISCOUNTS.ID</code>.
     */
    public final TableField<DiscountsRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.CODE</code>.
     */
    public final TableField<DiscountsRecord, String> CODE = createField(DSL.name("CODE"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.NAME</code>.
     */
    public final TableField<DiscountsRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.DISCOUNT_TYPE</code>.
     */
    public final TableField<DiscountsRecord, String> DISCOUNT_TYPE = createField(DSL.name("DISCOUNT_TYPE"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.DISCOUNT_VALUE</code>.
     */
    public final TableField<DiscountsRecord, BigDecimal> DISCOUNT_VALUE = createField(DSL.name("DISCOUNT_VALUE"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.MIN_PURCHASE</code>.
     */
    public final TableField<DiscountsRecord, BigDecimal> MIN_PURCHASE = createField(DSL.name("MIN_PURCHASE"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.ACTIVE</code>.
     */
    public final TableField<DiscountsRecord, Boolean> ACTIVE = createField(DSL.name("ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.VALID_FROM</code>.
     */
    public final TableField<DiscountsRecord, LocalDateTime> VALID_FROM = createField(DSL.name("VALID_FROM"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.VALID_UNTIL</code>.
     */
    public final TableField<DiscountsRecord, LocalDateTime> VALID_UNTIL = createField(DSL.name("VALID_UNTIL"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.CREATED_AT</code>.
     */
    public final TableField<DiscountsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Discounts(Name alias, Table<DiscountsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Discounts(Name alias, Table<DiscountsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.DISCOUNTS</code> table reference
     */
    public Discounts(String alias) {
        this(DSL.name(alias), DISCOUNTS);
    }

    /**
     * Create an aliased <code>PUBLIC.DISCOUNTS</code> table reference
     */
    public Discounts(Name alias) {
        this(alias, DISCOUNTS);
    }

    /**
     * Create a <code>PUBLIC.DISCOUNTS</code> table reference
     */
    public Discounts() {
        this(DSL.name("DISCOUNTS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DiscountsRecord, Long> getIdentity() {
        return (Identity<DiscountsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DiscountsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9E;
    }

    @Override
    public List<UniqueKey<DiscountsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_9ED);
    }

    @Override
    public Discounts as(String alias) {
        return new Discounts(DSL.name(alias), this);
    }

    @Override
    public Discounts as(Name alias) {
        return new Discounts(alias, this);
    }

    @Override
    public Discounts as(Table<?> alias) {
        return new Discounts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Discounts rename(String name) {
        return new Discounts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Discounts rename(Name name) {
        return new Discounts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Discounts rename(Table<?> name) {
        return new Discounts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discounts where(Condition condition) {
        return new Discounts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discounts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discounts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discounts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Discounts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Discounts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Discounts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Discounts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discounts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Discounts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
