/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables;


import com.turboboostteam.pos.jooq.Keys;
import com.turboboostteam.pos.jooq.Public;
import com.turboboostteam.pos.jooq.tables.Products.ProductsPath;
import com.turboboostteam.pos.jooq.tables.records.InventoryStockRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryStock extends TableImpl<InventoryStockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.INVENTORY_STOCK</code>
     */
    public static final InventoryStock INVENTORY_STOCK = new InventoryStock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoryStockRecord> getRecordType() {
        return InventoryStockRecord.class;
    }

    /**
     * The column <code>PUBLIC.INVENTORY_STOCK.ID</code>.
     */
    public final TableField<InventoryStockRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.INVENTORY_STOCK.PRODUCT_ID</code>.
     */
    public final TableField<InventoryStockRecord, Long> PRODUCT_ID = createField(DSL.name("PRODUCT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.INVENTORY_STOCK.QUANTITY</code>.
     */
    public final TableField<InventoryStockRecord, Integer> QUANTITY = createField(DSL.name("QUANTITY"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.INVENTORY_STOCK.LOW_STOCK_THRESHOLD</code>.
     */
    public final TableField<InventoryStockRecord, Integer> LOW_STOCK_THRESHOLD = createField(DSL.name("LOW_STOCK_THRESHOLD"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("5"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.INVENTORY_STOCK.UPDATED_AT</code>.
     */
    public final TableField<InventoryStockRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private InventoryStock(Name alias, Table<InventoryStockRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InventoryStock(Name alias, Table<InventoryStockRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.INVENTORY_STOCK</code> table reference
     */
    public InventoryStock(String alias) {
        this(DSL.name(alias), INVENTORY_STOCK);
    }

    /**
     * Create an aliased <code>PUBLIC.INVENTORY_STOCK</code> table reference
     */
    public InventoryStock(Name alias) {
        this(alias, INVENTORY_STOCK);
    }

    /**
     * Create a <code>PUBLIC.INVENTORY_STOCK</code> table reference
     */
    public InventoryStock() {
        this(DSL.name("INVENTORY_STOCK"), null);
    }

    public <O extends Record> InventoryStock(Table<O> path, ForeignKey<O, InventoryStockRecord> childPath, InverseForeignKey<O, InventoryStockRecord> parentPath) {
        super(path, childPath, parentPath, INVENTORY_STOCK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InventoryStockPath extends InventoryStock implements Path<InventoryStockRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InventoryStockPath(Table<O> path, ForeignKey<O, InventoryStockRecord> childPath, InverseForeignKey<O, InventoryStockRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InventoryStockPath(Name alias, Table<InventoryStockRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InventoryStockPath as(String alias) {
            return new InventoryStockPath(DSL.name(alias), this);
        }

        @Override
        public InventoryStockPath as(Name alias) {
            return new InventoryStockPath(alias, this);
        }

        @Override
        public InventoryStockPath as(Table<?> alias) {
            return new InventoryStockPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<InventoryStockRecord, Long> getIdentity() {
        return (Identity<InventoryStockRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<InventoryStockRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    @Override
    public List<ForeignKey<InventoryStockRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_3B);
    }

    private transient ProductsPath _products;

    /**
     * Get the implicit join path to the <code>PUBLIC.PRODUCTS</code> table.
     */
    public ProductsPath products() {
        if (_products == null)
            _products = new ProductsPath(this, Keys.CONSTRAINT_3B, null);

        return _products;
    }

    @Override
    public InventoryStock as(String alias) {
        return new InventoryStock(DSL.name(alias), this);
    }

    @Override
    public InventoryStock as(Name alias) {
        return new InventoryStock(alias, this);
    }

    @Override
    public InventoryStock as(Table<?> alias) {
        return new InventoryStock(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryStock rename(String name) {
        return new InventoryStock(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryStock rename(Name name) {
        return new InventoryStock(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryStock rename(Table<?> name) {
        return new InventoryStock(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryStock where(Condition condition) {
        return new InventoryStock(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryStock where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryStock where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryStock where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryStock where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryStock where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryStock where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryStock where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryStock whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryStock whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
