/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables;


import com.turboboostteam.pos.jooq.Keys;
import com.turboboostteam.pos.jooq.Public;
import com.turboboostteam.pos.jooq.tables.Sales.SalesPath;
import com.turboboostteam.pos.jooq.tables.records.PaymentsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Payments extends TableImpl<PaymentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.PAYMENTS</code>
     */
    public static final Payments PAYMENTS = new Payments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaymentsRecord> getRecordType() {
        return PaymentsRecord.class;
    }

    /**
     * The column <code>PUBLIC.PAYMENTS.ID</code>.
     */
    public final TableField<PaymentsRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.PAYMENTS.SALE_ID</code>.
     */
    public final TableField<PaymentsRecord, Long> SALE_ID = createField(DSL.name("SALE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.PAYMENTS.PAYMENT_TYPE</code>.
     */
    public final TableField<PaymentsRecord, String> PAYMENT_TYPE = createField(DSL.name("PAYMENT_TYPE"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.PAYMENTS.AMOUNT</code>.
     */
    public final TableField<PaymentsRecord, BigDecimal> AMOUNT = createField(DSL.name("AMOUNT"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.PAYMENTS.CURRENCY</code>.
     */
    public final TableField<PaymentsRecord, String> CURRENCY = createField(DSL.name("CURRENCY"), SQLDataType.VARCHAR(3).nullable(false).defaultValue(DSL.field(DSL.raw("'USD'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.PAYMENTS.REFERENCE</code>.
     */
    public final TableField<PaymentsRecord, String> REFERENCE = createField(DSL.name("REFERENCE"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.PAYMENTS.CREATED_AT</code>.
     */
    public final TableField<PaymentsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Payments(Name alias, Table<PaymentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Payments(Name alias, Table<PaymentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.PAYMENTS</code> table reference
     */
    public Payments(String alias) {
        this(DSL.name(alias), PAYMENTS);
    }

    /**
     * Create an aliased <code>PUBLIC.PAYMENTS</code> table reference
     */
    public Payments(Name alias) {
        this(alias, PAYMENTS);
    }

    /**
     * Create a <code>PUBLIC.PAYMENTS</code> table reference
     */
    public Payments() {
        this(DSL.name("PAYMENTS"), null);
    }

    public <O extends Record> Payments(Table<O> path, ForeignKey<O, PaymentsRecord> childPath, InverseForeignKey<O, PaymentsRecord> parentPath) {
        super(path, childPath, parentPath, PAYMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PaymentsPath extends Payments implements Path<PaymentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PaymentsPath(Table<O> path, ForeignKey<O, PaymentsRecord> childPath, InverseForeignKey<O, PaymentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PaymentsPath(Name alias, Table<PaymentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PaymentsPath as(String alias) {
            return new PaymentsPath(DSL.name(alias), this);
        }

        @Override
        public PaymentsPath as(Name alias) {
            return new PaymentsPath(alias, this);
        }

        @Override
        public PaymentsPath as(Table<?> alias) {
            return new PaymentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PaymentsRecord, Long> getIdentity() {
        return (Identity<PaymentsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PaymentsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    @Override
    public List<ForeignKey<PaymentsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_81);
    }

    private transient SalesPath _sales;

    /**
     * Get the implicit join path to the <code>PUBLIC.SALES</code> table.
     */
    public SalesPath sales() {
        if (_sales == null)
            _sales = new SalesPath(this, Keys.CONSTRAINT_81, null);

        return _sales;
    }

    @Override
    public Payments as(String alias) {
        return new Payments(DSL.name(alias), this);
    }

    @Override
    public Payments as(Name alias) {
        return new Payments(alias, this);
    }

    @Override
    public Payments as(Table<?> alias) {
        return new Payments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(String name) {
        return new Payments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(Name name) {
        return new Payments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(Table<?> name) {
        return new Payments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments where(Condition condition) {
        return new Payments(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
