/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables;


import com.turboboostteam.pos.jooq.Keys;
import com.turboboostteam.pos.jooq.Public;
import com.turboboostteam.pos.jooq.tables.Categories.CategoriesPath;
import com.turboboostteam.pos.jooq.tables.InventoryStock.InventoryStockPath;
import com.turboboostteam.pos.jooq.tables.SaleItems.SaleItemsPath;
import com.turboboostteam.pos.jooq.tables.StockMovements.StockMovementsPath;
import com.turboboostteam.pos.jooq.tables.records.ProductsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Products extends TableImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.PRODUCTS</code>
     */
    public static final Products PRODUCTS = new Products();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductsRecord> getRecordType() {
        return ProductsRecord.class;
    }

    /**
     * The column <code>PUBLIC.PRODUCTS.ID</code>.
     */
    public final TableField<ProductsRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.PRODUCTS.NAME</code>.
     */
    public final TableField<ProductsRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.PRODUCTS.BARCODE</code>.
     */
    public final TableField<ProductsRecord, String> BARCODE = createField(DSL.name("BARCODE"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>PUBLIC.PRODUCTS.PRICE</code>.
     */
    public final TableField<ProductsRecord, BigDecimal> PRICE = createField(DSL.name("PRICE"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.PRODUCTS.CURRENCY</code>.
     */
    public final TableField<ProductsRecord, String> CURRENCY = createField(DSL.name("CURRENCY"), SQLDataType.VARCHAR(3).nullable(false).defaultValue(DSL.field(DSL.raw("'USD'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.PRODUCTS.PRODUCT_TYPE</code>.
     */
    public final TableField<ProductsRecord, String> PRODUCT_TYPE = createField(DSL.name("PRODUCT_TYPE"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'SIMPLE'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.PRODUCTS.CATEGORY_ID</code>.
     */
    public final TableField<ProductsRecord, Long> CATEGORY_ID = createField(DSL.name("CATEGORY_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>PUBLIC.PRODUCTS.ACTIVE</code>.
     */
    public final TableField<ProductsRecord, Boolean> ACTIVE = createField(DSL.name("ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>PUBLIC.PRODUCTS.CREATED_AT</code>.
     */
    public final TableField<ProductsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Products(Name alias, Table<ProductsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Products(Name alias, Table<ProductsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.PRODUCTS</code> table reference
     */
    public Products(String alias) {
        this(DSL.name(alias), PRODUCTS);
    }

    /**
     * Create an aliased <code>PUBLIC.PRODUCTS</code> table reference
     */
    public Products(Name alias) {
        this(alias, PRODUCTS);
    }

    /**
     * Create a <code>PUBLIC.PRODUCTS</code> table reference
     */
    public Products() {
        this(DSL.name("PRODUCTS"), null);
    }

    public <O extends Record> Products(Table<O> path, ForeignKey<O, ProductsRecord> childPath, InverseForeignKey<O, ProductsRecord> parentPath) {
        super(path, childPath, parentPath, PRODUCTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProductsPath extends Products implements Path<ProductsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProductsPath(Table<O> path, ForeignKey<O, ProductsRecord> childPath, InverseForeignKey<O, ProductsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProductsPath(Name alias, Table<ProductsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProductsPath as(String alias) {
            return new ProductsPath(DSL.name(alias), this);
        }

        @Override
        public ProductsPath as(Name alias) {
            return new ProductsPath(alias, this);
        }

        @Override
        public ProductsPath as(Table<?> alias) {
            return new ProductsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ProductsRecord, Long> getIdentity() {
        return (Identity<ProductsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_F;
    }

    @Override
    public List<UniqueKey<ProductsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_F2);
    }

    @Override
    public List<ForeignKey<ProductsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_F2D);
    }

    private transient CategoriesPath _categories;

    /**
     * Get the implicit join path to the <code>PUBLIC.CATEGORIES</code> table.
     */
    public CategoriesPath categories() {
        if (_categories == null)
            _categories = new CategoriesPath(this, Keys.CONSTRAINT_F2D, null);

        return _categories;
    }

    private transient InventoryStockPath _inventoryStock;

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.INVENTORY_STOCK</code> table
     */
    public InventoryStockPath inventoryStock() {
        if (_inventoryStock == null)
            _inventoryStock = new InventoryStockPath(this, null, Keys.CONSTRAINT_3B.getInverseKey());

        return _inventoryStock;
    }

    private transient SaleItemsPath _saleItems;

    /**
     * Get the implicit to-many join path to the <code>PUBLIC.SALE_ITEMS</code>
     * table
     */
    public SaleItemsPath saleItems() {
        if (_saleItems == null)
            _saleItems = new SaleItemsPath(this, null, Keys.CONSTRAINT_985F.getInverseKey());

        return _saleItems;
    }

    private transient StockMovementsPath _stockMovements;

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.STOCK_MOVEMENTS</code> table
     */
    public StockMovementsPath stockMovements() {
        if (_stockMovements == null)
            _stockMovements = new StockMovementsPath(this, null, Keys.CONSTRAINT_99.getInverseKey());

        return _stockMovements;
    }

    @Override
    public Products as(String alias) {
        return new Products(DSL.name(alias), this);
    }

    @Override
    public Products as(Name alias) {
        return new Products(alias, this);
    }

    @Override
    public Products as(Table<?> alias) {
        return new Products(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(String name) {
        return new Products(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(Name name) {
        return new Products(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(Table<?> name) {
        return new Products(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Condition condition) {
        return new Products(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
