/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables;


import com.turboboostteam.pos.jooq.Keys;
import com.turboboostteam.pos.jooq.Public;
import com.turboboostteam.pos.jooq.tables.Payments.PaymentsPath;
import com.turboboostteam.pos.jooq.tables.SaleItems.SaleItemsPath;
import com.turboboostteam.pos.jooq.tables.Users.UsersPath;
import com.turboboostteam.pos.jooq.tables.records.SalesRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sales extends TableImpl<SalesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.SALES</code>
     */
    public static final Sales SALES = new Sales();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SalesRecord> getRecordType() {
        return SalesRecord.class;
    }

    /**
     * The column <code>PUBLIC.SALES.ID</code>.
     */
    public final TableField<SalesRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.SALES.SALE_NUMBER</code>.
     */
    public final TableField<SalesRecord, String> SALE_NUMBER = createField(DSL.name("SALE_NUMBER"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SALES.CASHIER_ID</code>.
     */
    public final TableField<SalesRecord, Long> CASHIER_ID = createField(DSL.name("CASHIER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SALES.STATUS</code>.
     */
    public final TableField<SalesRecord, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'OPEN'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.SALES.SUBTOTAL</code>.
     */
    public final TableField<SalesRecord, BigDecimal> SUBTOTAL = createField(DSL.name("SUBTOTAL"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>PUBLIC.SALES.TAX_AMOUNT</code>.
     */
    public final TableField<SalesRecord, BigDecimal> TAX_AMOUNT = createField(DSL.name("TAX_AMOUNT"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>PUBLIC.SALES.DISCOUNT_AMOUNT</code>.
     */
    public final TableField<SalesRecord, BigDecimal> DISCOUNT_AMOUNT = createField(DSL.name("DISCOUNT_AMOUNT"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>PUBLIC.SALES.TOTAL_AMOUNT</code>.
     */
    public final TableField<SalesRecord, BigDecimal> TOTAL_AMOUNT = createField(DSL.name("TOTAL_AMOUNT"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>PUBLIC.SALES.CURRENCY</code>.
     */
    public final TableField<SalesRecord, String> CURRENCY = createField(DSL.name("CURRENCY"), SQLDataType.VARCHAR(3).nullable(false).defaultValue(DSL.field(DSL.raw("'USD'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.SALES.CREATED_AT</code>.
     */
    public final TableField<SalesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.SALES.COMPLETED_AT</code>.
     */
    public final TableField<SalesRecord, LocalDateTime> COMPLETED_AT = createField(DSL.name("COMPLETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private Sales(Name alias, Table<SalesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sales(Name alias, Table<SalesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.SALES</code> table reference
     */
    public Sales(String alias) {
        this(DSL.name(alias), SALES);
    }

    /**
     * Create an aliased <code>PUBLIC.SALES</code> table reference
     */
    public Sales(Name alias) {
        this(alias, SALES);
    }

    /**
     * Create a <code>PUBLIC.SALES</code> table reference
     */
    public Sales() {
        this(DSL.name("SALES"), null);
    }

    public <O extends Record> Sales(Table<O> path, ForeignKey<O, SalesRecord> childPath, InverseForeignKey<O, SalesRecord> parentPath) {
        super(path, childPath, parentPath, SALES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SalesPath extends Sales implements Path<SalesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SalesPath(Table<O> path, ForeignKey<O, SalesRecord> childPath, InverseForeignKey<O, SalesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SalesPath(Name alias, Table<SalesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SalesPath as(String alias) {
            return new SalesPath(DSL.name(alias), this);
        }

        @Override
        public SalesPath as(Name alias) {
            return new SalesPath(alias, this);
        }

        @Override
        public SalesPath as(Table<?> alias) {
            return new SalesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SalesRecord, Long> getIdentity() {
        return (Identity<SalesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SalesRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4B;
    }

    @Override
    public List<UniqueKey<SalesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_4B0);
    }

    @Override
    public List<ForeignKey<SalesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_4B05);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>PUBLIC.USERS</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.CONSTRAINT_4B05, null);

        return _users;
    }

    private transient PaymentsPath _payments;

    /**
     * Get the implicit to-many join path to the <code>PUBLIC.PAYMENTS</code>
     * table
     */
    public PaymentsPath payments() {
        if (_payments == null)
            _payments = new PaymentsPath(this, null, Keys.CONSTRAINT_81.getInverseKey());

        return _payments;
    }

    private transient SaleItemsPath _saleItems;

    /**
     * Get the implicit to-many join path to the <code>PUBLIC.SALE_ITEMS</code>
     * table
     */
    public SaleItemsPath saleItems() {
        if (_saleItems == null)
            _saleItems = new SaleItemsPath(this, null, Keys.CONSTRAINT_985.getInverseKey());

        return _saleItems;
    }

    @Override
    public Sales as(String alias) {
        return new Sales(DSL.name(alias), this);
    }

    @Override
    public Sales as(Name alias) {
        return new Sales(alias, this);
    }

    @Override
    public Sales as(Table<?> alias) {
        return new Sales(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sales rename(String name) {
        return new Sales(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sales rename(Name name) {
        return new Sales(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sales rename(Table<?> name) {
        return new Sales(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales where(Condition condition) {
        return new Sales(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sales where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sales where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sales where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sales where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
