/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables;


import com.turboboostteam.pos.jooq.Keys;
import com.turboboostteam.pos.jooq.Public;
import com.turboboostteam.pos.jooq.tables.Products.ProductsPath;
import com.turboboostteam.pos.jooq.tables.Sales.SalesPath;
import com.turboboostteam.pos.jooq.tables.records.SaleItemsRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SaleItems extends TableImpl<SaleItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.SALE_ITEMS</code>
     */
    public static final SaleItems SALE_ITEMS = new SaleItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SaleItemsRecord> getRecordType() {
        return SaleItemsRecord.class;
    }

    /**
     * The column <code>PUBLIC.SALE_ITEMS.ID</code>.
     */
    public final TableField<SaleItemsRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.SALE_ITEMS.SALE_ID</code>.
     */
    public final TableField<SaleItemsRecord, Long> SALE_ID = createField(DSL.name("SALE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SALE_ITEMS.PRODUCT_ID</code>.
     */
    public final TableField<SaleItemsRecord, Long> PRODUCT_ID = createField(DSL.name("PRODUCT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SALE_ITEMS.PRODUCT_NAME</code>.
     */
    public final TableField<SaleItemsRecord, String> PRODUCT_NAME = createField(DSL.name("PRODUCT_NAME"), SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SALE_ITEMS.QUANTITY</code>.
     */
    public final TableField<SaleItemsRecord, Integer> QUANTITY = createField(DSL.name("QUANTITY"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.SALE_ITEMS.UNIT_PRICE</code>.
     */
    public final TableField<SaleItemsRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("UNIT_PRICE"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SALE_ITEMS.TAX_AMOUNT</code>.
     */
    public final TableField<SaleItemsRecord, BigDecimal> TAX_AMOUNT = createField(DSL.name("TAX_AMOUNT"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>PUBLIC.SALE_ITEMS.DISCOUNT_AMOUNT</code>.
     */
    public final TableField<SaleItemsRecord, BigDecimal> DISCOUNT_AMOUNT = createField(DSL.name("DISCOUNT_AMOUNT"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>PUBLIC.SALE_ITEMS.LINE_TOTAL</code>.
     */
    public final TableField<SaleItemsRecord, BigDecimal> LINE_TOTAL = createField(DSL.name("LINE_TOTAL"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SALE_ITEMS.CURRENCY</code>.
     */
    public final TableField<SaleItemsRecord, String> CURRENCY = createField(DSL.name("CURRENCY"), SQLDataType.VARCHAR(3).nullable(false).defaultValue(DSL.field(DSL.raw("'USD'"), SQLDataType.VARCHAR)), this, "");

    private SaleItems(Name alias, Table<SaleItemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SaleItems(Name alias, Table<SaleItemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.SALE_ITEMS</code> table reference
     */
    public SaleItems(String alias) {
        this(DSL.name(alias), SALE_ITEMS);
    }

    /**
     * Create an aliased <code>PUBLIC.SALE_ITEMS</code> table reference
     */
    public SaleItems(Name alias) {
        this(alias, SALE_ITEMS);
    }

    /**
     * Create a <code>PUBLIC.SALE_ITEMS</code> table reference
     */
    public SaleItems() {
        this(DSL.name("SALE_ITEMS"), null);
    }

    public <O extends Record> SaleItems(Table<O> path, ForeignKey<O, SaleItemsRecord> childPath, InverseForeignKey<O, SaleItemsRecord> parentPath) {
        super(path, childPath, parentPath, SALE_ITEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SaleItemsPath extends SaleItems implements Path<SaleItemsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SaleItemsPath(Table<O> path, ForeignKey<O, SaleItemsRecord> childPath, InverseForeignKey<O, SaleItemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SaleItemsPath(Name alias, Table<SaleItemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SaleItemsPath as(String alias) {
            return new SaleItemsPath(DSL.name(alias), this);
        }

        @Override
        public SaleItemsPath as(Name alias) {
            return new SaleItemsPath(alias, this);
        }

        @Override
        public SaleItemsPath as(Table<?> alias) {
            return new SaleItemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SaleItemsRecord, Long> getIdentity() {
        return (Identity<SaleItemsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SaleItemsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_98;
    }

    @Override
    public List<ForeignKey<SaleItemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_985, Keys.CONSTRAINT_985F);
    }

    private transient SalesPath _sales;

    /**
     * Get the implicit join path to the <code>PUBLIC.SALES</code> table.
     */
    public SalesPath sales() {
        if (_sales == null)
            _sales = new SalesPath(this, Keys.CONSTRAINT_985, null);

        return _sales;
    }

    private transient ProductsPath _products;

    /**
     * Get the implicit join path to the <code>PUBLIC.PRODUCTS</code> table.
     */
    public ProductsPath products() {
        if (_products == null)
            _products = new ProductsPath(this, Keys.CONSTRAINT_985F, null);

        return _products;
    }

    @Override
    public SaleItems as(String alias) {
        return new SaleItems(DSL.name(alias), this);
    }

    @Override
    public SaleItems as(Name alias) {
        return new SaleItems(alias, this);
    }

    @Override
    public SaleItems as(Table<?> alias) {
        return new SaleItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SaleItems rename(String name) {
        return new SaleItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SaleItems rename(Name name) {
        return new SaleItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SaleItems rename(Table<?> name) {
        return new SaleItems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleItems where(Condition condition) {
        return new SaleItems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleItems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleItems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleItems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SaleItems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SaleItems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SaleItems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SaleItems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleItems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleItems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
