/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq.tables;


import com.turboboostteam.pos.jooq.Keys;
import com.turboboostteam.pos.jooq.Public;
import com.turboboostteam.pos.jooq.tables.Products.ProductsPath;
import com.turboboostteam.pos.jooq.tables.records.StockMovementsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StockMovements extends TableImpl<StockMovementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.STOCK_MOVEMENTS</code>
     */
    public static final StockMovements STOCK_MOVEMENTS = new StockMovements();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StockMovementsRecord> getRecordType() {
        return StockMovementsRecord.class;
    }

    /**
     * The column <code>PUBLIC.STOCK_MOVEMENTS.ID</code>.
     */
    public final TableField<StockMovementsRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.STOCK_MOVEMENTS.PRODUCT_ID</code>.
     */
    public final TableField<StockMovementsRecord, Long> PRODUCT_ID = createField(DSL.name("PRODUCT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.STOCK_MOVEMENTS.MOVEMENT_TYPE</code>.
     */
    public final TableField<StockMovementsRecord, String> MOVEMENT_TYPE = createField(DSL.name("MOVEMENT_TYPE"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.STOCK_MOVEMENTS.QUANTITY_CHANGE</code>.
     */
    public final TableField<StockMovementsRecord, Integer> QUANTITY_CHANGE = createField(DSL.name("QUANTITY_CHANGE"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.STOCK_MOVEMENTS.NOTES</code>.
     */
    public final TableField<StockMovementsRecord, String> NOTES = createField(DSL.name("NOTES"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.STOCK_MOVEMENTS.CREATED_BY</code>.
     */
    public final TableField<StockMovementsRecord, String> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>PUBLIC.STOCK_MOVEMENTS.CREATED_AT</code>.
     */
    public final TableField<StockMovementsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private StockMovements(Name alias, Table<StockMovementsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StockMovements(Name alias, Table<StockMovementsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.STOCK_MOVEMENTS</code> table reference
     */
    public StockMovements(String alias) {
        this(DSL.name(alias), STOCK_MOVEMENTS);
    }

    /**
     * Create an aliased <code>PUBLIC.STOCK_MOVEMENTS</code> table reference
     */
    public StockMovements(Name alias) {
        this(alias, STOCK_MOVEMENTS);
    }

    /**
     * Create a <code>PUBLIC.STOCK_MOVEMENTS</code> table reference
     */
    public StockMovements() {
        this(DSL.name("STOCK_MOVEMENTS"), null);
    }

    public <O extends Record> StockMovements(Table<O> path, ForeignKey<O, StockMovementsRecord> childPath, InverseForeignKey<O, StockMovementsRecord> parentPath) {
        super(path, childPath, parentPath, STOCK_MOVEMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StockMovementsPath extends StockMovements implements Path<StockMovementsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StockMovementsPath(Table<O> path, ForeignKey<O, StockMovementsRecord> childPath, InverseForeignKey<O, StockMovementsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StockMovementsPath(Name alias, Table<StockMovementsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StockMovementsPath as(String alias) {
            return new StockMovementsPath(DSL.name(alias), this);
        }

        @Override
        public StockMovementsPath as(Name alias) {
            return new StockMovementsPath(alias, this);
        }

        @Override
        public StockMovementsPath as(Table<?> alias) {
            return new StockMovementsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<StockMovementsRecord, Long> getIdentity() {
        return (Identity<StockMovementsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<StockMovementsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    @Override
    public List<ForeignKey<StockMovementsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_99);
    }

    private transient ProductsPath _products;

    /**
     * Get the implicit join path to the <code>PUBLIC.PRODUCTS</code> table.
     */
    public ProductsPath products() {
        if (_products == null)
            _products = new ProductsPath(this, Keys.CONSTRAINT_99, null);

        return _products;
    }

    @Override
    public StockMovements as(String alias) {
        return new StockMovements(DSL.name(alias), this);
    }

    @Override
    public StockMovements as(Name alias) {
        return new StockMovements(alias, this);
    }

    @Override
    public StockMovements as(Table<?> alias) {
        return new StockMovements(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StockMovements rename(String name) {
        return new StockMovements(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StockMovements rename(Name name) {
        return new StockMovements(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StockMovements rename(Table<?> name) {
        return new StockMovements(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StockMovements where(Condition condition) {
        return new StockMovements(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StockMovements where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StockMovements where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StockMovements where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StockMovements where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StockMovements where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StockMovements where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StockMovements where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StockMovements whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StockMovements whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
