/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq;


import com.turboboostteam.pos.jooq.tables.Categories;
import com.turboboostteam.pos.jooq.tables.InventoryStock;
import com.turboboostteam.pos.jooq.tables.Products;
import com.turboboostteam.pos.jooq.tables.StockMovements;
import com.turboboostteam.pos.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.CATEGORIES</code>.
     */
    public final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>PUBLIC.INVENTORY_STOCK</code>.
     */
    public final InventoryStock INVENTORY_STOCK = InventoryStock.INVENTORY_STOCK;

    /**
     * The table <code>PUBLIC.PRODUCTS</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>PUBLIC.STOCK_MOVEMENTS</code>.
     */
    public final StockMovements STOCK_MOVEMENTS = StockMovements.STOCK_MOVEMENTS;

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Categories.CATEGORIES,
            InventoryStock.INVENTORY_STOCK,
            Products.PRODUCTS,
            StockMovements.STOCK_MOVEMENTS,
            Users.USERS
        );
    }
}
