/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq;


import com.turboboostteam.pos.jooq.tables.Categories;
import com.turboboostteam.pos.jooq.tables.Products;
import com.turboboostteam.pos.jooq.tables.Users;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.CATEGORIES</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>PUBLIC.PRODUCTS</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
