/*
 * This file is generated by jOOQ.
 */
package com.turboboostteam.pos.jooq;


import com.turboboostteam.pos.jooq.tables.Categories;
import com.turboboostteam.pos.jooq.tables.Customers;
import com.turboboostteam.pos.jooq.tables.Discounts;
import com.turboboostteam.pos.jooq.tables.InventoryStock;
import com.turboboostteam.pos.jooq.tables.Payments;
import com.turboboostteam.pos.jooq.tables.Products;
import com.turboboostteam.pos.jooq.tables.SaleItems;
import com.turboboostteam.pos.jooq.tables.Sales;
import com.turboboostteam.pos.jooq.tables.StockMovements;
import com.turboboostteam.pos.jooq.tables.Users;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.CATEGORIES</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>PUBLIC.CUSTOMERS</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>PUBLIC.DISCOUNTS</code>.
     */
    public static final Discounts DISCOUNTS = Discounts.DISCOUNTS;

    /**
     * The table <code>PUBLIC.INVENTORY_STOCK</code>.
     */
    public static final InventoryStock INVENTORY_STOCK = InventoryStock.INVENTORY_STOCK;

    /**
     * The table <code>PUBLIC.PAYMENTS</code>.
     */
    public static final Payments PAYMENTS = Payments.PAYMENTS;

    /**
     * The table <code>PUBLIC.PRODUCTS</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>PUBLIC.SALE_ITEMS</code>.
     */
    public static final SaleItems SALE_ITEMS = SaleItems.SALE_ITEMS;

    /**
     * The table <code>PUBLIC.SALES</code>.
     */
    public static final Sales SALES = Sales.SALES;

    /**
     * The table <code>PUBLIC.STOCK_MOVEMENTS</code>.
     */
    public static final StockMovements STOCK_MOVEMENTS = StockMovements.STOCK_MOVEMENTS;

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
